name: PP-Python-App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Sync latest code on self-hosted runner
        run: |
          echo "Pulling the latest code..."
          cd /home/octaloop/Python-CI-CD/actions-runner/Python-CI-CD
          git pull origin main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'



      - name: Run tests
        run: pytest

      - name: Build Docker image
        run: docker build --no-cache -t python-cicd-image  .

      - name: Check if the container is running, then stop and remove it
        run: |
          if docker ps -q --filter "name=python-cicd-container"; then
            echo "Stopping and removing container python-cicd-container..."
            docker stop python-cicd-container || true
            docker rm python-cicd-container || true
          else
            echo "Container python-cicd-container is not running. Skipping stop and remove."
          fi

      - name: Run Docker container
        run: docker run -d -p 3000:3000 --name python-cicd-container python-cicd-image
